various new stuff

diff --git a/bash/scope b/bash/scope
--- a/bash/scope
+++ b/bash/scope
@@ -1,4 +1,5 @@
 # -*- sh -*-
+# shellcheck shell=bash
 
 iii=outside
 echo " iii at top=$iii"
@@ -95,3 +96,27 @@ echo "${indent}script, after func1 call: func2_var='$func2_var'"
 echo "${indent}script, after func1 call: declared='$declared'"
 echo "${indent}script, after func1 call: localed='$localed'"
 echo "${indent}script, after func1 call: func_declared_twice='$func_declared_twice'"
+
+echo "() vs {}"
+
+function returntester_braces ()
+{
+    false || { echo "failure in ${FUNCNAME[0]}" && return 43; }
+    echo "${FUNCNAME[0]}: We shouldn't be here and status=$?"
+}
+
+function returntester_parens ()
+{
+    false || ( echo "failure in ${FUNCNAME[0]}" && return 53 )
+    echo "${FUNCNAME[0]}: We shouldn't be here and return status=$?"
+    false || ( echo "failure in ${FUNCNAME[0]}" && exit 54 )
+    echo "${FUNCNAME[0]}: We shouldn't be here and exit status=$?"
+}
+
+echo "calling returntester_braces..."
+returntester_braces
+echo "back from returntester_braces and status=$?"
+echo
+echo "calling returntester_parens"
+returntester_parens
+echo "back from returntester_parens and status=$?"
